drop table temp_branch;
drop table branch;

create external table temp_branch  ( BRANCH_CODE string,
									 BRANCH_NAME string,
									BRANCH_STREET string,
									BRANCH_CITY string, 
									BRANCH_STATE string, 
									BRANCH_ZIP string,
									BRANCH_PHONE string,
								    LAST_UPDATED timestamp)
row format delimited 
fields terminated by '\t'
stored as textfile
location '/user/maria_dev/Credit_Card_System/branch/CDW_SAPP_D_BRANCH';
